name: Hetzner Image Build
description: Builds a snapshot image on the Hetzner cloud
inputs:
  template:
    description: Path to template file
    required: true
  token:
    description: Token used to access Hetzner API
    required: true
  build-identifier:
    description: Content of build label attached to every instance and ssh-key for identifying resources (for cleanup)
    required: true
runs:
  using: composite
  steps:
    - name: Setup `packer`
      uses: hashicorp/setup-packer@main
      id: setup
      with:
        version: "latest"

    - name: Run `packer init`
      id: init
      shell: bash
      run: |
        packer init ${{ inputs.template }}

    - name: Run `packer validate`
      id: validate
      shell: bash
      run: |
        packer validate -var hcloud_token=${{ inputs.token }} -var build_identifier=${{ inputs.build-identifier }} ${{ inputs.template }}

    - name: Run `packer build`
      shell: bash
      run: |
        packer build -color=false -force -on-error=cleanup -var hcloud_token=${{ inputs.token }} -var build_identifier=${{ inputs.build-identifier }} -var github_branch=${{ github.ref_name }} -var version=latest ${{ inputs.template }}
